name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-
    steps:
      - uses: actions/checkout
      - uses: oven-sh/setup-bun
        with:
          bun-version: latest
      - run: bun install
      - run: bun test
